export const API_ROUTES = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
  },
  MESSENGER: {
    THREADS: '/messenger/threads',
    MESSAGES: (threadId: string) => `/messenger/threads/${threadId}/messages`,
    ALIVE: (threadId: string) => `/messenger/threads/${threadId}/alive`,
    REQUEST: '/messenger/request',
    ACCEPT: (threadId: string) => `/messenger/threads/${threadId}/accept`,
    REJECT: (threadId: string) => `/messenger/threads/${threadId}/reject`,
    READ: (threadId: string) => `/messenger/threads/${threadId}/read`,
  },
  PACKAGES: {
    SEARCH: '/packages/search',
  },
  BOOKINGS: {
    BASE: '/bookings',
    CREATE: '/booking',
    STATUS: (id: string) => `/bookings/${id}/status`,
    CANCEL: (id: string) => `/bookings/${id}/cancel`,
    DAMAGE: (id: string) => `/bookings/${id}/damage`,
    DISPUTE: (id: string) => `/bookings/${id}/dispute`,
    LOGS: (id: string) => `/bookings/${id}/logs`,
  },
  ADMIN: {
    BOOKINGS: '/support/bookings',
    ASSIGN_BOOKING: (id: string) => `/admin/bookings/${id}/assign`,
  },
  VENDOR_PACKAGES: {
    BASE: '/vendor/packages',
    BY_ID: (id: string) => `/vendor/packages/${id}`,
    STATUS: (id: string) => `/vendor/packages/${id}/status`,
    IMAGES: (id: string) => `/vendor/packages/${id}/images`,
  },
  CUSTOMER: {
    PROFILE: '/profile',
    DASHBOARD: '/customer/dashboard',
  },
  EVENT_CATEGORIES: '/event-categories',
  RFPS: {
    MY: '/rfps',
  },
  SERVICE_CATEGORIES: '/service-categories',
  NOTIFICATIONS: {
    BASE: '/notifications',
    READ_ALL: '/notifications/read-all',
  },
  SUPPORT: {
    DASHBOARD_STATS: '/support/stats',
    TICKETS_BASE: '/support/tickets',
    CREATE_TICKET: '/support/ticket',
    TICKET_BY_ID: (id: string) => `/support/tickets/${id}`,
    TICKET_REPLY: (id: string) => `/support/tickets/${id}/reply`,
    TICKET_STATUS: (id: string) => `/support/tickets/${id}/status`,
    PENDING_VENDORS: '/support/vendors/pending',
    VERIFY_VENDOR: (id: string) => `/support/vendors/${id}/verify`,
    PENDING_PACKAGES: '/support/packages/pending',
    VERIFY_PACKAGE: (id: string) => `/support/packages/${id}/verify`,
    BOOKINGS: '/support/bookings',
    BOOKING_NOTE: (id: string) => `/support/bookings/${id}/note`,
    BOOKING_USER_UPDATE: (id: string) => `/support/bookings/${id}/user-update`,
    BOOKING_VENDOR_REMINDER: (id: string) => `/support/bookings/${id}/vendor-reminder`,
    FLAGGED_REVIEWS: '/support/reviews/flagged',
    MODERATE_REVIEW: (id: string) => `/support/reviews/${id}/moderate`,
  },
  VENDOR: {
    PROFILE: '/vendor/profile',
    DASHBOARD: '/vendor/dashboard',
    TASKS: '/vendor/dashboard/tasks',
    ANALYTICS: '/vendor/analytics',
    COLLABORATIONS: '/vendor/collaborations',
    COLLABORATION_ACCEPT: (id: string) => `/vendor/collaborations/${id}/accept`,
    ENQUIRIES: '/vendor/enquiries',
    ENQUIRY_REPLY: (id: string) => `/vendor/enquiries/${id}/reply`,
    LOYALTY: '/vendor/loyalty',
    GROWTH_TARGET: '/vendor/growth-target',
    ESG_IMPACT: '/vendor/esg-impact',
  },
  COMMISSION: {
    CONFIG: '/commission/config',
    CALCULATE: '/commission/calculate',
    RATES: '/commission/rates',
  },
  SUBSCRIPTION: {
    CURRENT: '/vendor/subscription',
    UPGRADE: '/vendor/subscription/upgrade',
    CANCEL: '/vendor/subscription/cancel',
    HISTORY: '/vendor/subscription/history',
  },
  GUARANTEE: {
    POLICIES: '/guarantee/policies',
    CLAIM: '/guarantee/claim',
    CLAIMS: '/guarantee/claims',
  },
  INVOICES: {
    VENDOR: '/vendor/invoices',
    ADMIN: '/admin/invoices',
    DOWNLOAD: (id: string) => `/invoices/${id}/download`,
  },
  REVIEWS: {
    BASE: '/reviews',
  },
  LOYALTY: {
    BALANCE: '/loyalty/balance',
    HISTORY: '/loyalty/history',
    REDEEM: '/loyalty/redeem',
    CALCULATE_DISCOUNT: '/loyalty/calculate-discount',
    REFER: '/loyalty/refer',
    REVIEW: '/loyalty/review',
  },
};
